[SPC-level-clue]
text = '''
All levels start with one prexisting image and text clue.

Additional clues can be unlocked 
'''

[TST-level]
text = '''
All levels start with one prexisting image and text clue.

Additional clues can be unlocked 
'''

[TST-level-clue]
text = '''
All levels start with one prexisting image and text clue.

Additional clues can be unlocked 
'''