[SPC-account]
text = '''
Displays user account info and provides account
related functionality.
'''

[SPC-account-title]
text = '''
Username is displayed on the top of the page.
'''

[SPC-account-auth_provider_info]
text = '''
Additional information like email or facebook account name.
'''

[SPC-account-delete]
text = '''
Deletes the account remove all data related to it from the site.

When confirming deletion, a warning is displayed
about the user being removed from the hall of fame.
'''