[SPC-getting_started]
partof = 'REQ-tk_app'
text = '''
Instructions for playing the game

* Background on puzzles
* Where to get help
* Tools needed
* FAQ

Source of page hard-coded as html template
'''

[TST-getting_started]
text = '''
Navigate to the getting started page and verify that the title exists.
'''